# stat_arb_trader_dhan/data_feeds/instrument_manager.py

import pandas as pd
from core.logger_setup import logger

# (The NIFTY50_INTERNAL_LIST remains the same as before)
NIFTY50_INTERNAL_LIST = [
    {"CompanyName": "360 ONE WAM Ltd.", "NSESymbol": "360ONE", "Sector": "Financial Services", "ISIN": "INE466L01038"},
    {"CompanyName": "3M India Ltd.", "NSESymbol": "3MINDIA", "Sector": "Diversified", "ISIN": "INE470A01017"},
    {"CompanyName": "ABB India Ltd.", "NSESymbol": "ABB", "Sector": "Capital Goods", "ISIN": "INE117A01022"},
    {"CompanyName": "ACC Ltd.", "NSESymbol": "ACC", "Sector": "Construction Materials", "ISIN": "INE012A01025"},
    {"CompanyName": "ACME Solar Holdings Ltd.", "NSESymbol": "ACMESOLAR", "Sector": "Power", "ISIN": "INE622W01025"},
    {"CompanyName": "AIA Engineering Ltd.", "NSESymbol": "AIAENG", "Sector": "Capital Goods", "ISIN": "INE212H01026"},
    {"CompanyName": "APL Apollo Tubes Ltd.", "NSESymbol": "APLAPOLLO", "Sector": "Capital Goods", "ISIN": "INE702C01027"},
    {"CompanyName": "AU Small Finance Bank Ltd.", "NSESymbol": "AUBANK", "Sector": "Financial Services", "ISIN": "INE949L01017"},
    {"CompanyName": "AWL Agri Business Ltd.", "NSESymbol": "AWL", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE699H01024"},
    {"CompanyName": "Aadhar Housing Finance Ltd.", "NSESymbol": "AADHARHFC", "Sector": "Financial Services", "ISIN": "INE883F01010"},
    {"CompanyName": "Aarti Industries Ltd.", "NSESymbol": "AARTIIND", "Sector": "Chemicals", "ISIN": "INE769A01020"},
    {"CompanyName": "Aavas Financiers Ltd.", "NSESymbol": "AAVAS", "Sector": "Financial Services", "ISIN": "INE216P01012"},
    {"CompanyName": "Abbott India Ltd.", "NSESymbol": "ABBOTINDIA", "Sector": "Healthcare", "ISIN": "INE358A01014"},
    {"CompanyName": "Action Construction Equipment Ltd.", "NSESymbol": "ACE", "Sector": "Capital Goods", "ISIN": "INE731H01025"},
    {"CompanyName": "Adani Energy Solutions Ltd.", "NSESymbol": "ADANIENSOL", "Sector": "Power", "ISIN": "INE931S01010"},
    {"CompanyName": "Adani Enterprises Ltd.", "NSESymbol": "ADANIENT", "Sector": "Metals & Mining", "ISIN": "INE423A01024"},
    {"CompanyName": "Adani Green Energy Ltd.", "NSESymbol": "ADANIGREEN", "Sector": "Power", "ISIN": "INE364U01010"},
    {"CompanyName": "Adani Ports and Special Economic Zone Ltd.", "NSESymbol": "ADANIPORTS", "Sector": "Services", "ISIN": "INE742F01042"},
    {"CompanyName": "Adani Power Ltd.", "NSESymbol": "ADANIPOWER", "Sector": "Power", "ISIN": "INE814H01011"},
    {"CompanyName": "Adani Total Gas Ltd.", "NSESymbol": "ATGL", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE399L01023"},
    {"CompanyName": "Aditya Birla Capital Ltd.", "NSESymbol": "ABCAPITAL", "Sector": "Financial Services", "ISIN": "INE674K01013"},
    {"CompanyName": "Aditya Birla Fashion and Retail Ltd.", "NSESymbol": "ABFRL", "Sector": "Consumer Services", "ISIN": "INE647O01011"},
    {"CompanyName": "Aditya Birla Real Estate Ltd.", "NSESymbol": "ABREL", "Sector": "Forest Materials", "ISIN": "INE055A01016"},
    {"CompanyName": "Aditya Birla Sun Life AMC Ltd.", "NSESymbol": "ABSLAMC", "Sector": "Financial Services", "ISIN": "INE404A01024"},
    {"CompanyName": "Aegis Logistics Ltd.", "NSESymbol": "AEGISLOG", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE208C01025"},
    {"CompanyName": "Afcons Infrastructure Ltd.", "NSESymbol": "AFCONS", "Sector": "Construction", "ISIN": "INE101I01011"},
    {"CompanyName": "Affle 3i Ltd.", "NSESymbol": "AFFLE", "Sector": "Information Technology", "ISIN": "INE00WC01027"},
    {"CompanyName": "Ajanta Pharmaceuticals Ltd.", "NSESymbol": "AJANTPHARM", "Sector": "Healthcare", "ISIN": "INE031B01049"},
    {"CompanyName": "Akums Drugs and Pharmaceuticals Ltd.", "NSESymbol": "AKUMS", "Sector": "Healthcare", "ISIN": "INE09XN01023"},
    {"CompanyName": "Alembic Pharmaceuticals Ltd.", "NSESymbol": "APLLTD", "Sector": "Healthcare", "ISIN": "INE901L01018"},
    {"CompanyName": "Alivus Life Sciences Ltd.", "NSESymbol": "ALIVUS", "Sector": "Healthcare", "ISIN": "INE03Q201024"},
    {"CompanyName": "Alkem Laboratories Ltd.", "NSESymbol": "ALKEM", "Sector": "Healthcare", "ISIN": "INE540L01014"},
    {"CompanyName": "Alkyl Amines Chemicals Ltd.", "NSESymbol": "ALKYLAMINE", "Sector": "Chemicals", "ISIN": "INE150B01039"},
    {"CompanyName": "Alok Industries Ltd.", "NSESymbol": "ALOKINDS", "Sector": "Textiles", "ISIN": "INE270A01029"},
    {"CompanyName": "Amara Raja Energy & Mobility Ltd.", "NSESymbol": "ARE&M", "Sector": "Automobile and Auto Components", "ISIN": "INE885A01032"},
    {"CompanyName": "Amber Enterprises India Ltd.", "NSESymbol": "AMBER", "Sector": "Consumer Durables", "ISIN": "INE371P01015"},
    {"CompanyName": "Ambuja Cements Ltd.", "NSESymbol": "AMBUJACEM", "Sector": "Construction Materials", "ISIN": "INE079A01024"},
    {"CompanyName": "Anand Rathi Wealth Ltd.", "NSESymbol": "ANANDRATHI", "Sector": "Financial Services", "ISIN": "INE463V01026"},
    {"CompanyName": "Anant Raj Ltd.", "NSESymbol": "ANANTRAJ", "Sector": "Realty", "ISIN": "INE242C01024"},
    {"CompanyName": "Angel One Ltd.", "NSESymbol": "ANGELONE", "Sector": "Financial Services", "ISIN": "INE732I01013"},
    {"CompanyName": "Apar Industries Ltd.", "NSESymbol": "APARINDS", "Sector": "Capital Goods", "ISIN": "INE372A01015"},
    {"CompanyName": "Apollo Hospitals Enterprise Ltd.", "NSESymbol": "APOLLOHOSP", "Sector": "Healthcare", "ISIN": "INE437A01024"},
    {"CompanyName": "Apollo Tyres Ltd.", "NSESymbol": "APOLLOTYRE", "Sector": "Automobile and Auto Components", "ISIN": "INE438A01022"},
    {"CompanyName": "Aptus Value Housing Finance India Ltd.", "NSESymbol": "APTUS", "Sector": "Financial Services", "ISIN": "INE852O01025"},
    {"CompanyName": "Asahi India Glass Ltd.", "NSESymbol": "ASAHIINDIA", "Sector": "Automobile and Auto Components", "ISIN": "INE439A01020"},
    {"CompanyName": "Ashok Leyland Ltd.", "NSESymbol": "ASHOKLEY", "Sector": "Capital Goods", "ISIN": "INE208A01029"},
    {"CompanyName": "Asian Paints Ltd.", "NSESymbol": "ASIANPAINT", "Sector": "Consumer Durables", "ISIN": "INE021A01026"},
    {"CompanyName": "Aster DM Healthcare Ltd.", "NSESymbol": "ASTERDM", "Sector": "Healthcare", "ISIN": "INE914M01019"},
    {"CompanyName": "AstraZenca Pharma India Ltd.", "NSESymbol": "ASTRAZEN", "Sector": "Healthcare", "ISIN": "INE203A01020"},
    {"CompanyName": "Astral Ltd.", "NSESymbol": "ASTRAL", "Sector": "Capital Goods", "ISIN": "INE006I01046"},
    {"CompanyName": "Atul Ltd.", "NSESymbol": "ATUL", "Sector": "Chemicals", "ISIN": "INE100A01010"},
    {"CompanyName": "Aurobindo Pharma Ltd.", "NSESymbol": "AUROPHARMA", "Sector": "Healthcare", "ISIN": "INE406A01037"},
    {"CompanyName": "Authum Investment & Infrastructure Ltd.", "NSESymbol": "AIIL", "Sector": "Financial Services", "ISIN": "INE206F01022"},
    {"CompanyName": "Avenue Supermarts Ltd.", "NSESymbol": "DMART", "Sector": "Consumer Services", "ISIN": "INE192R01011"},
    {"CompanyName": "Axis Bank Ltd.", "NSESymbol": "AXISBANK", "Sector": "Financial Services", "ISIN": "INE238A01034"},
    {"CompanyName": "BASF India Ltd.", "NSESymbol": "BASF", "Sector": "Chemicals", "ISIN": "INE373A01013"},
    {"CompanyName": "BEML Ltd.", "NSESymbol": "BEML", "Sector": "Capital Goods", "ISIN": "INE258A01016"},
    {"CompanyName": "BLS International Services Ltd.", "NSESymbol": "BLS", "Sector": "Consumer Services", "ISIN": "INE153T01027"},
    {"CompanyName": "BSE Ltd.", "NSESymbol": "BSE", "Sector": "Financial Services", "ISIN": "INE118H01025"},
    {"CompanyName": "Bajaj Auto Ltd.", "NSESymbol": "BAJAJ-AUTO", "Sector": "Automobile and Auto Components", "ISIN": "INE917I01010"},
    {"CompanyName": "Bajaj Finance Ltd.", "NSESymbol": "BAJFINANCE", "Sector": "Financial Services", "ISIN": "INE296A01032"},
    {"CompanyName": "Bajaj Finserv Ltd.", "NSESymbol": "BAJAJFINSV", "Sector": "Financial Services", "ISIN": "INE918I01026"},
    {"CompanyName": "Bajaj Holdings & Investment Ltd.", "NSESymbol": "BAJAJHLDNG", "Sector": "Financial Services", "ISIN": "INE118A01012"},
    {"CompanyName": "Bajaj Housing Finance Ltd.", "NSESymbol": "BAJAJHFL", "Sector": "Financial Services", "ISIN": "INE377Y01014"},
    {"CompanyName": "Balkrishna Industries Ltd.", "NSESymbol": "BALKRISIND", "Sector": "Automobile and Auto Components", "ISIN": "INE787D01026"},
    {"CompanyName": "Balrampur Chini Mills Ltd.", "NSESymbol": "BALRAMCHIN", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE119A01028"},
    {"CompanyName": "Bandhan Bank Ltd.", "NSESymbol": "BANDHANBNK", "Sector": "Financial Services", "ISIN": "INE545U01014"},
    {"CompanyName": "Bank of Baroda", "NSESymbol": "BANKBARODA", "Sector": "Financial Services", "ISIN": "INE028A01039"},
    {"CompanyName": "Bank of India", "NSESymbol": "BANKINDIA", "Sector": "Financial Services", "ISIN": "INE084A01016"},
    {"CompanyName": "Bank of Maharashtra", "NSESymbol": "MAHABANK", "Sector": "Financial Services", "ISIN": "INE457A01014"},
    {"CompanyName": "Bata India Ltd.", "NSESymbol": "BATAINDIA", "Sector": "Consumer Durables", "ISIN": "INE176A01028"},
    {"CompanyName": "Bayer Cropscience Ltd.", "NSESymbol": "BAYERCROP", "Sector": "Chemicals", "ISIN": "INE462A01022"},
    {"CompanyName": "Berger Paints India Ltd.", "NSESymbol": "BERGEPAINT", "Sector": "Consumer Durables", "ISIN": "INE463A01038"},
    {"CompanyName": "Bharat Dynamics Ltd.", "NSESymbol": "BDL", "Sector": "Capital Goods", "ISIN": "INE171Z01026"},
    {"CompanyName": "Bharat Electronics Ltd.", "NSESymbol": "BEL", "Sector": "Capital Goods", "ISIN": "INE263A01024"},
    {"CompanyName": "Bharat Forge Ltd.", "NSESymbol": "BHARATFORG", "Sector": "Automobile and Auto Components", "ISIN": "INE465A01025"},
    {"CompanyName": "Bharat Heavy Electricals Ltd.", "NSESymbol": "BHEL", "Sector": "Capital Goods", "ISIN": "INE257A01026"},
    {"CompanyName": "Bharat Petroleum Corporation Ltd.", "NSESymbol": "BPCL", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE029A01011"},
    {"CompanyName": "Bharti Airtel Ltd.", "NSESymbol": "BHARTIARTL", "Sector": "Telecommunication", "ISIN": "INE397D01024"},
    {"CompanyName": "Bharti Hexacom Ltd.", "NSESymbol": "BHARTIHEXA", "Sector": "Telecommunication", "ISIN": "INE343G01021"},
    {"CompanyName": "Bikaji Foods International Ltd.", "NSESymbol": "BIKAJI", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE00E101023"},
    {"CompanyName": "Biocon Ltd.", "NSESymbol": "BIOCON", "Sector": "Healthcare", "ISIN": "INE376G01013"},
    {"CompanyName": "Birlasoft Ltd.", "NSESymbol": "BSOFT", "Sector": "Information Technology", "ISIN": "INE836A01035"},
    {"CompanyName": "Blue Dart Express Ltd.", "NSESymbol": "BLUEDART", "Sector": "Services", "ISIN": "INE233B01017"},
    {"CompanyName": "Blue Star Ltd.", "NSESymbol": "BLUESTARCO", "Sector": "Consumer Durables", "ISIN": "INE472A01039"},
    {"CompanyName": "Bombay Burmah Trading Corporation Ltd.", "NSESymbol": "BBTC", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE050A01025"},
    {"CompanyName": "Bosch Ltd.", "NSESymbol": "BOSCHLTD", "Sector": "Automobile and Auto Components", "ISIN": "INE323A01026"},
    {"CompanyName": "Brainbees Solutions Ltd.", "NSESymbol": "FIRSTCRY", "Sector": "Consumer Services", "ISIN": "INE02RE01045"},
    {"CompanyName": "Brigade Enterprises Ltd.", "NSESymbol": "BRIGADE", "Sector": "Realty", "ISIN": "INE791I01019"},
    {"CompanyName": "Britannia Industries Ltd.", "NSESymbol": "BRITANNIA", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE216A01030"},
    {"CompanyName": "C.E. Info Systems Ltd.", "NSESymbol": "MAPMYINDIA", "Sector": "Information Technology", "ISIN": "INE0BV301023"},
    {"CompanyName": "CCL Products (I) Ltd.", "NSESymbol": "CCL", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE421D01022"},
    {"CompanyName": "CESC Ltd.", "NSESymbol": "CESC", "Sector": "Power", "ISIN": "INE486A01021"},
    {"CompanyName": "CG Power and Industrial Solutions Ltd.", "NSESymbol": "CGPOWER", "Sector": "Capital Goods", "ISIN": "INE067A01029"},
    {"CompanyName": "CRISIL Ltd.", "NSESymbol": "CRISIL", "Sector": "Financial Services", "ISIN": "INE007A01025"},
    {"CompanyName": "Campus Activewear Ltd.", "NSESymbol": "CAMPUS", "Sector": "Consumer Durables", "ISIN": "INE278Y01022"},
    {"CompanyName": "Can Fin Homes Ltd.", "NSESymbol": "CANFINHOME", "Sector": "Financial Services", "ISIN": "INE477A01020"},
    {"CompanyName": "Canara Bank", "NSESymbol": "CANBK", "Sector": "Financial Services", "ISIN": "INE476A01022"},
    {"CompanyName": "Caplin Point Laboratories Ltd.", "NSESymbol": "CAPLIPOINT", "Sector": "Healthcare", "ISIN": "INE475E01026"},
    {"CompanyName": "Capri Global Capital Ltd.", "NSESymbol": "CGCL", "Sector": "Financial Services", "ISIN": "INE180C01042"},
    {"CompanyName": "Carborundum Universal Ltd.", "NSESymbol": "CARBORUNIV", "Sector": "Capital Goods", "ISIN": "INE120A01034"},
    {"CompanyName": "Castrol India Ltd.", "NSESymbol": "CASTROLIND", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE172A01027"},
    {"CompanyName": "Ceat Ltd.", "NSESymbol": "CEATLTD", "Sector": "Automobile and Auto Components", "ISIN": "INE482A01020"},
    {"CompanyName": "Central Bank of India", "NSESymbol": "CENTRALBK", "Sector": "Financial Services", "ISIN": "INE483A01010"},
    {"CompanyName": "Central Depository Services (India) Ltd.", "NSESymbol": "CDSL", "Sector": "Financial Services", "ISIN": "INE736A01011"},
    {"CompanyName": "Century Plyboards (India) Ltd.", "NSESymbol": "CENTURYPLY", "Sector": "Consumer Durables", "ISIN": "INE348B01021"},
    {"CompanyName": "Cera Sanitaryware Ltd", "NSESymbol": "CERA", "Sector": "Consumer Durables", "ISIN": "INE739E01017"},
    {"CompanyName": "Chalet Hotels Ltd.", "NSESymbol": "CHALET", "Sector": "Consumer Services", "ISIN": "INE427F01016"},
    {"CompanyName": "Chambal Fertilizers & Chemicals Ltd.", "NSESymbol": "CHAMBLFERT", "Sector": "Chemicals", "ISIN": "INE085A01013"},
    {"CompanyName": "Chennai Petroleum Corporation Ltd.", "NSESymbol": "CHENNPETRO", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE178A01016"},
    {"CompanyName": "Cholamandalam Financial Holdings Ltd.", "NSESymbol": "CHOLAHLDNG", "Sector": "Financial Services", "ISIN": "INE149A01033"},
    {"CompanyName": "Cholamandalam Investment and Finance Company Ltd.", "NSESymbol": "CHOLAFIN", "Sector": "Financial Services", "ISIN": "INE121A01024"},
    {"CompanyName": "Cipla Ltd.", "NSESymbol": "CIPLA", "Sector": "Healthcare", "ISIN": "INE059A01026"},
    {"CompanyName": "City Union Bank Ltd.", "NSESymbol": "CUB", "Sector": "Financial Services", "ISIN": "INE491A01021"},
    {"CompanyName": "Clean Science and Technology Ltd.", "NSESymbol": "CLEAN", "Sector": "Chemicals", "ISIN": "INE227W01023"},
    {"CompanyName": "Coal India Ltd.", "NSESymbol": "COALINDIA", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE522F01014"},
    {"CompanyName": "Cochin Shipyard Ltd.", "NSESymbol": "COCHINSHIP", "Sector": "Capital Goods", "ISIN": "INE704P01025"},
    {"CompanyName": "Coforge Ltd.", "NSESymbol": "COFORGE", "Sector": "Information Technology", "ISIN": "INE591G01025"},
    {"CompanyName": "Cohance Lifesciences Ltd.", "NSESymbol": "COHANCE", "Sector": "Healthcare", "ISIN": "INE03QK01018"},
    {"CompanyName": "Colgate Palmolive (India) Ltd.", "NSESymbol": "COLPAL", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE259A01022"},
    {"CompanyName": "Computer Age Management Services Ltd.", "NSESymbol": "CAMS", "Sector": "Financial Services", "ISIN": "INE596I01012"},
    {"CompanyName": "Concord Biotech Ltd.", "NSESymbol": "CONCORDBIO", "Sector": "Healthcare", "ISIN": "INE338H01029"},
    {"CompanyName": "Container Corporation of India Ltd.", "NSESymbol": "CONCOR", "Sector": "Services", "ISIN": "INE111A01025"},
    {"CompanyName": "Coromandel International Ltd.", "NSESymbol": "COROMANDEL", "Sector": "Chemicals", "ISIN": "INE169A01031"},
    {"CompanyName": "Craftsman Automation Ltd.", "NSESymbol": "CRAFTSMAN", "Sector": "Automobile and Auto Components", "ISIN": "INE00LO01017"},
    {"CompanyName": "CreditAccess Grameen Ltd.", "NSESymbol": "CREDITACC", "Sector": "Financial Services", "ISIN": "INE741K01010"},
    {"CompanyName": "Crompton Greaves Consumer Electricals Ltd.", "NSESymbol": "CROMPTON", "Sector": "Consumer Durables", "ISIN": "INE299U01018"},
    {"CompanyName": "Cummins India Ltd.", "NSESymbol": "CUMMINSIND", "Sector": "Capital Goods", "ISIN": "INE298A01020"},
    {"CompanyName": "Cyient Ltd.", "NSESymbol": "CYIENT", "Sector": "Information Technology", "ISIN": "INE136B01020"},
    {"CompanyName": "DCM Shriram Ltd.", "NSESymbol": "DCMSHRIRAM", "Sector": "Diversified", "ISIN": "INE499A01024"},
    {"CompanyName": "DLF Ltd.", "NSESymbol": "DLF", "Sector": "Realty", "ISIN": "INE271C01023"},
    {"CompanyName": "DOMS Industries Ltd.", "NSESymbol": "DOMS", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE321T01012"},
    {"CompanyName": "Dabur India Ltd.", "NSESymbol": "DABUR", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE016A01026"},
    {"CompanyName": "Dalmia Bharat Ltd.", "NSESymbol": "DALBHARAT", "Sector": "Construction Materials", "ISIN": "INE00R701025"},
    {"CompanyName": "Data Patterns (India) Ltd.", "NSESymbol": "DATAPATTNS", "Sector": "Capital Goods", "ISIN": "INE0IX101010"},
    {"CompanyName": "Deepak Fertilisers & Petrochemicals Corp. Ltd.", "NSESymbol": "DEEPAKFERT", "Sector": "Chemicals", "ISIN": "INE501A01019"},
    {"CompanyName": "Deepak Nitrite Ltd.", "NSESymbol": "DEEPAKNTR", "Sector": "Chemicals", "ISIN": "INE288B01029"},
    {"CompanyName": "Delhivery Ltd.", "NSESymbol": "DELHIVERY", "Sector": "Services", "ISIN": "INE148O01028"},
    {"CompanyName": "Devyani International Ltd.", "NSESymbol": "DEVYANI", "Sector": "Consumer Services", "ISIN": "INE872J01023"},
    {"CompanyName": "Divi's Laboratories Ltd.", "NSESymbol": "DIVISLAB", "Sector": "Healthcare", "ISIN": "INE361B01024"},
    {"CompanyName": "Dixon Technologies (India) Ltd.", "NSESymbol": "DIXON", "Sector": "Consumer Durables", "ISIN": "INE935N01020"},
    {"CompanyName": "Dr. Lal Path Labs Ltd.", "NSESymbol": "LALPATHLAB", "Sector": "Healthcare", "ISIN": "INE600L01024"},
    {"CompanyName": "Dr. Reddy's Laboratories Ltd.", "NSESymbol": "DRREDDY", "Sector": "Healthcare", "ISIN": "INE089A01031"},
    {"CompanyName": "Dummy2 Raymond Ltd.", "NSESymbol": "DUMMYRAYMN", "Sector": "Realty", "ISIN": "DUM2301A0101"},
    {"CompanyName": "E.I.D. Parry (India) Ltd.", "NSESymbol": "EIDPARRY", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE126A01031"},
    {"CompanyName": "EIH Ltd.", "NSESymbol": "EIHOTEL", "Sector": "Consumer Services", "ISIN": "INE230A01023"},
    {"CompanyName": "Eicher Motors Ltd.", "NSESymbol": "EICHERMOT", "Sector": "Automobile and Auto Components", "ISIN": "INE066A01021"},
    {"CompanyName": "Elecon Engineering Co. Ltd.", "NSESymbol": "ELECON", "Sector": "Capital Goods", "ISIN": "INE205B01031"},
    {"CompanyName": "Elgi Equipments Ltd.", "NSESymbol": "ELGIEQUIP", "Sector": "Capital Goods", "ISIN": "INE285A01027"},
    {"CompanyName": "Emami Ltd.", "NSESymbol": "EMAMILTD", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE548C01032"},
    {"CompanyName": "Emcure Pharmaceuticals Ltd.", "NSESymbol": "EMCURE", "Sector": "Healthcare", "ISIN": "INE168P01015"},
    {"CompanyName": "Endurance Technologies Ltd.", "NSESymbol": "ENDURANCE", "Sector": "Automobile and Auto Components", "ISIN": "INE913H01037"},
    {"CompanyName": "Engineers India Ltd.", "NSESymbol": "ENGINERSIN", "Sector": "Construction", "ISIN": "INE510A01028"},
    {"CompanyName": "Eris Lifesciences Ltd.", "NSESymbol": "ERIS", "Sector": "Healthcare", "ISIN": "INE406M01024"},
    {"CompanyName": "Escorts Kubota Ltd.", "NSESymbol": "ESCORTS", "Sector": "Capital Goods", "ISIN": "INE042A01014"},
    {"CompanyName": "Eternal Ltd.", "NSESymbol": "ETERNAL", "Sector": "Consumer Services", "ISIN": "INE758T01015"},
    {"CompanyName": "Exide Industries Ltd.", "NSESymbol": "EXIDEIND", "Sector": "Automobile and Auto Components", "ISIN": "INE302A01020"},
    {"CompanyName": "FSN E-Commerce Ventures Ltd.", "NSESymbol": "NYKAA", "Sector": "Consumer Services", "ISIN": "INE388Y01029"},
    {"CompanyName": "Federal Bank Ltd.", "NSESymbol": "FEDERALBNK", "Sector": "Financial Services", "ISIN": "INE171A01029"},
    {"CompanyName": "Fertilisers and Chemicals Travancore Ltd.", "NSESymbol": "FACT", "Sector": "Chemicals", "ISIN": "INE188A01015"},
    {"CompanyName": "Finolex Cables Ltd.", "NSESymbol": "FINCABLES", "Sector": "Capital Goods", "ISIN": "INE235A01022"},
    {"CompanyName": "Finolex Industries Ltd.", "NSESymbol": "FINPIPE", "Sector": "Capital Goods", "ISIN": "INE183A01024"},
    {"CompanyName": "Firstsource Solutions Ltd.", "NSESymbol": "FSL", "Sector": "Services", "ISIN": "INE684F01012"},
    {"CompanyName": "Five-Star Business Finance Ltd.", "NSESymbol": "FIVESTAR", "Sector": "Financial Services", "ISIN": "INE128S01021"},
    {"CompanyName": "Fortis Healthcare Ltd.", "NSESymbol": "FORTIS", "Sector": "Healthcare", "ISIN": "INE061F01013"},
    {"CompanyName": "GAIL (India) Ltd.", "NSESymbol": "GAIL", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE129A01019"},
    {"CompanyName": "GE Vernova T&D India Ltd.", "NSESymbol": "GVT&D", "Sector": "Capital Goods", "ISIN": "INE200A01026"},
    {"CompanyName": "GMR Airports Ltd.", "NSESymbol": "GMRAIRPORT", "Sector": "Services", "ISIN": "INE776C01039"},
    {"CompanyName": "Garden Reach Shipbuilders & Engineers Ltd.", "NSESymbol": "GRSE", "Sector": "Capital Goods", "ISIN": "INE382Z01011"},
    {"CompanyName": "General Insurance Corporation of India", "NSESymbol": "GICRE", "Sector": "Financial Services", "ISIN": "INE481Y01014"},
    {"CompanyName": "Gillette India Ltd.", "NSESymbol": "GILLETTE", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE322A01010"},
    {"CompanyName": "Gland Pharma Ltd.", "NSESymbol": "GLAND", "Sector": "Healthcare", "ISIN": "INE068V01023"},
    {"CompanyName": "Glaxosmithkline Pharmaceuticals Ltd.", "NSESymbol": "GLAXO", "Sector": "Healthcare", "ISIN": "INE159A01016"},
    {"CompanyName": "Glenmark Pharmaceuticals Ltd.", "NSESymbol": "GLENMARK", "Sector": "Healthcare", "ISIN": "INE935A01035"},
    {"CompanyName": "Global Health Ltd.", "NSESymbol": "MEDANTA", "Sector": "Healthcare", "ISIN": "INE474Q01031"},
    {"CompanyName": "Go Digit General Insurance Ltd.", "NSESymbol": "GODIGIT", "Sector": "Financial Services", "ISIN": "INE03JT01014"},
    {"CompanyName": "Godawari Power & Ispat Ltd.", "NSESymbol": "GPIL", "Sector": "Capital Goods", "ISIN": "INE177H01039"},
    {"CompanyName": "Godfrey Phillips India Ltd.", "NSESymbol": "GODFRYPHLP", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE260B01028"},
    {"CompanyName": "Godrej Agrovet Ltd.", "NSESymbol": "GODREJAGRO", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE850D01014"},
    {"CompanyName": "Godrej Consumer Products Ltd.", "NSESymbol": "GODREJCP", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE102D01028"},
    {"CompanyName": "Godrej Industries Ltd.", "NSESymbol": "GODREJIND", "Sector": "Diversified", "ISIN": "INE233A01035"},
    {"CompanyName": "Godrej Properties Ltd.", "NSESymbol": "GODREJPROP", "Sector": "Realty", "ISIN": "INE484J01027"},
    {"CompanyName": "Granules India Ltd.", "NSESymbol": "GRANULES", "Sector": "Healthcare", "ISIN": "INE101D01020"},
    {"CompanyName": "Graphite India Ltd.", "NSESymbol": "GRAPHITE", "Sector": "Capital Goods", "ISIN": "INE371A01025"},
    {"CompanyName": "Grasim Industries Ltd.", "NSESymbol": "GRASIM", "Sector": "Construction Materials", "ISIN": "INE047A01021"},
    {"CompanyName": "Gravita India Ltd.", "NSESymbol": "GRAVITA", "Sector": "Metals & Mining", "ISIN": "INE024L01027"},
    {"CompanyName": "Great Eastern Shipping Co. Ltd.", "NSESymbol": "GESHIP", "Sector": "Services", "ISIN": "INE017A01032"},
    {"CompanyName": "Gujarat Fluorochemicals Ltd.", "NSESymbol": "FLUOROCHEM", "Sector": "Chemicals", "ISIN": "INE09N301011"},
    {"CompanyName": "Gujarat Gas Ltd.", "NSESymbol": "GUJGASLTD", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE844O01030"},
    {"CompanyName": "Gujarat Mineral Development Corporation Ltd.", "NSESymbol": "GMDCLTD", "Sector": "Metals & Mining", "ISIN": "INE131A01031"},
    {"CompanyName": "Gujarat Narmada Valley Fertilizers and Chemicals Ltd.", "NSESymbol": "GNFC", "Sector": "Chemicals", "ISIN": "INE113A01013"},
    {"CompanyName": "Gujarat Pipavav Port Ltd.", "NSESymbol": "GPPL", "Sector": "Services", "ISIN": "INE517F01014"},
    {"CompanyName": "Gujarat State Petronet Ltd.", "NSESymbol": "GSPL", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE246F01010"},
    {"CompanyName": "H.E.G. Ltd.", "NSESymbol": "HEG", "Sector": "Capital Goods", "ISIN": "INE545A01024"},
    {"CompanyName": "HBL Engineering Ltd.", "NSESymbol": "HBLENGINE", "Sector": "Capital Goods", "ISIN": "INE292B01021"},
    {"CompanyName": "HCL Technologies Ltd.", "NSESymbol": "HCLTECH", "Sector": "Information Technology", "ISIN": "INE860A01027"},
    {"CompanyName": "HDFC Asset Management Company Ltd.", "NSESymbol": "HDFCAMC", "Sector": "Financial Services", "ISIN": "INE127D01025"},
    {"CompanyName": "HDFC Bank Ltd.", "NSESymbol": "HDFCBANK", "Sector": "Financial Services", "ISIN": "INE040A01034"},
    {"CompanyName": "HDFC Life Insurance Company Ltd.", "NSESymbol": "HDFCLIFE", "Sector": "Financial Services", "ISIN": "INE795G01014"},
    {"CompanyName": "HFCL Ltd.", "NSESymbol": "HFCL", "Sector": "Telecommunication", "ISIN": "INE548A01028"},
    {"CompanyName": "Happiest Minds Technologies Ltd.", "NSESymbol": "HAPPSTMNDS", "Sector": "Information Technology", "ISIN": "INE419U01012"},
    {"CompanyName": "Havells India Ltd.", "NSESymbol": "HAVELLS", "Sector": "Consumer Durables", "ISIN": "INE176B01034"},
    {"CompanyName": "Hero MotoCorp Ltd.", "NSESymbol": "HEROMOTOCO", "Sector": "Automobile and Auto Components", "ISIN": "INE158A01026"},
    {"CompanyName": "Himadri Speciality Chemical Ltd.", "NSESymbol": "HSCL", "Sector": "Chemicals", "ISIN": "INE019C01026"},
    {"CompanyName": "Hindalco Industries Ltd.", "NSESymbol": "HINDALCO", "Sector": "Metals & Mining", "ISIN": "INE038A01020"},
    {"CompanyName": "Hindustan Aeronautics Ltd.", "NSESymbol": "HAL", "Sector": "Capital Goods", "ISIN": "INE066F01020"},
    {"CompanyName": "Hindustan Copper Ltd.", "NSESymbol": "HINDCOPPER", "Sector": "Metals & Mining", "ISIN": "INE531E01026"},
    {"CompanyName": "Hindustan Petroleum Corporation Ltd.", "NSESymbol": "HINDPETRO", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE094A01015"},
    {"CompanyName": "Hindustan Unilever Ltd.", "NSESymbol": "HINDUNILVR", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE030A01027"},
    {"CompanyName": "Hindustan Zinc Ltd.", "NSESymbol": "HINDZINC", "Sector": "Metals & Mining", "ISIN": "INE267A01025"},
    {"CompanyName": "Hitachi Energy India Ltd.", "NSESymbol": "POWERINDIA", "Sector": "Capital Goods", "ISIN": "INE07Y701011"},
    {"CompanyName": "Home First Finance Company India Ltd.", "NSESymbol": "HOMEFIRST", "Sector": "Financial Services", "ISIN": "INE481N01025"},
    {"CompanyName": "Honasa Consumer Ltd.", "NSESymbol": "HONASA", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE0J5401028"},
    {"CompanyName": "Honeywell Automation India Ltd.", "NSESymbol": "HONAUT", "Sector": "Capital Goods", "ISIN": "INE671A01010"},
    {"CompanyName": "Housing & Urban Development Corporation Ltd.", "NSESymbol": "HUDCO", "Sector": "Financial Services", "ISIN": "INE031A01017"},
    {"CompanyName": "Hyundai Motor India Ltd.", "NSESymbol": "HYUNDAI", "Sector": "Automobile and Auto Components", "ISIN": "INE0V6F01027"},
    {"CompanyName": "ICICI Bank Ltd.", "NSESymbol": "ICICIBANK", "Sector": "Financial Services", "ISIN": "INE090A01021"},
    {"CompanyName": "ICICI Lombard General Insurance Company Ltd.", "NSESymbol": "ICICIGI", "Sector": "Financial Services", "ISIN": "INE765G01017"},
    {"CompanyName": "ICICI Prudential Life Insurance Company Ltd.", "NSESymbol": "ICICIPRULI", "Sector": "Financial Services", "ISIN": "INE726G01019"},
    {"CompanyName": "IDBI Bank Ltd.", "NSESymbol": "IDBI", "Sector": "Financial Services", "ISIN": "INE008A01015"},
    {"CompanyName": "IDFC First Bank Ltd.", "NSESymbol": "IDFCFIRSTB", "Sector": "Financial Services", "ISIN": "INE092T01019"},
    {"CompanyName": "IFCI Ltd.", "NSESymbol": "IFCI", "Sector": "Financial Services", "ISIN": "INE039A01010"},
    {"CompanyName": "IIFL Finance Ltd.", "NSESymbol": "IIFL", "Sector": "Financial Services", "ISIN": "INE530B01024"},
    {"CompanyName": "INOX India Ltd.", "NSESymbol": "INOXINDIA", "Sector": "Capital Goods", "ISIN": "INE616N01034"},
    {"CompanyName": "IRB Infrastructure Developers Ltd.", "NSESymbol": "IRB", "Sector": "Construction", "ISIN": "INE821I01022"},
    {"CompanyName": "IRCON International Ltd.", "NSESymbol": "IRCON", "Sector": "Construction", "ISIN": "INE962Y01021"},
    {"CompanyName": "ITC Ltd.", "NSESymbol": "ITC", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE154A01025"},
    {"CompanyName": "ITI Ltd.", "NSESymbol": "ITI", "Sector": "Telecommunication", "ISIN": "INE248A01017"},
    {"CompanyName": "Indegene Ltd.", "NSESymbol": "INDGN", "Sector": "Healthcare", "ISIN": "INE065X01017"},
    {"CompanyName": "India Cements Ltd.", "NSESymbol": "INDIACEM", "Sector": "Construction Materials", "ISIN": "INE383A01012"},
    {"CompanyName": "Indiamart Intermesh Ltd.", "NSESymbol": "INDIAMART", "Sector": "Consumer Services", "ISIN": "INE933S01016"},
    {"CompanyName": "Indian Bank", "NSESymbol": "INDIANB", "Sector": "Financial Services", "ISIN": "INE562A01011"},
    {"CompanyName": "Indian Energy Exchange Ltd.", "NSESymbol": "IEX", "Sector": "Financial Services", "ISIN": "INE022Q01020"},
    {"CompanyName": "Indian Hotels Co. Ltd.", "NSESymbol": "INDHOTEL", "Sector": "Consumer Services", "ISIN": "INE053A01029"},
    {"CompanyName": "Indian Oil Corporation Ltd.", "NSESymbol": "IOC", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE242A01010"},
    {"CompanyName": "Indian Overseas Bank", "NSESymbol": "IOB", "Sector": "Financial Services", "ISIN": "INE565A01014"},
    {"CompanyName": "Indian Railway Catering And Tourism Corporation Ltd.", "NSESymbol": "IRCTC", "Sector": "Consumer Services", "ISIN": "INE335Y01020"},
    {"CompanyName": "Indian Railway Finance Corporation Ltd.", "NSESymbol": "IRFC", "Sector": "Financial Services", "ISIN": "INE053F01016"},
    {"CompanyName": "Indian Renewable Energy Development Agency Ltd.", "NSESymbol": "IREDA", "Sector": "Financial Services", "ISIN": "INE202E01016"},
    {"CompanyName": "Indraprastha Gas Ltd.", "NSESymbol": "IGL", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE203G01027"},
    {"CompanyName": "Indus Towers Ltd.", "NSESymbol": "INDUSTOWER", "Sector": "Telecommunication", "ISIN": "INE121J01017"},
    {"CompanyName": "IndusInd Bank Ltd.", "NSESymbol": "INDUSINDBK", "Sector": "Financial Services", "ISIN": "INE095A01012"},
    {"CompanyName": "Info Edge (India) Ltd.", "NSESymbol": "NAUKRI", "Sector": "Consumer Services", "ISIN": "INE663F01032"},
    {"CompanyName": "Infosys Ltd.", "NSESymbol": "INFY", "Sector": "Information Technology", "ISIN": "INE009A01021"},
    {"CompanyName": "Inox Wind Ltd.", "NSESymbol": "INOXWIND", "Sector": "Capital Goods", "ISIN": "INE066P01011"},
    {"CompanyName": "Intellect Design Arena Ltd.", "NSESymbol": "INTELLECT", "Sector": "Information Technology", "ISIN": "INE306R01017"},
    {"CompanyName": "InterGlobe Aviation Ltd.", "NSESymbol": "INDIGO", "Sector": "Services", "ISIN": "INE646L01027"},
    {"CompanyName": "International Gemmological Institute (India) Ltd.", "NSESymbol": "IGIL", "Sector": "Services", "ISIN": "INE0Q9301021"},
    {"CompanyName": "Inventurus Knowledge Solutions Ltd.", "NSESymbol": "IKS", "Sector": "Information Technology", "ISIN": "INE115Q01022"},
    {"CompanyName": "Ipca Laboratories Ltd.", "NSESymbol": "IPCALAB", "Sector": "Healthcare", "ISIN": "INE571A01038"},
    {"CompanyName": "J.B. Chemicals & Pharmaceuticals Ltd.", "NSESymbol": "JBCHEPHARM", "Sector": "Healthcare", "ISIN": "INE572A01036"},
    {"CompanyName": "J.K. Cement Ltd.", "NSESymbol": "JKCEMENT", "Sector": "Construction Materials", "ISIN": "INE823G01014"},
    {"CompanyName": "JBM Auto Ltd.", "NSESymbol": "JBMA", "Sector": "Automobile and Auto Components", "ISIN": "INE927D01051"},
    {"CompanyName": "JK Tyre & Industries Ltd.", "NSESymbol": "JKTYRE", "Sector": "Automobile and Auto Components", "ISIN": "INE573A01042"},
    {"CompanyName": "JM Financial Ltd.", "NSESymbol": "JMFINANCIL", "Sector": "Financial Services", "ISIN": "INE780C01023"},
    {"CompanyName": "JSW Energy Ltd.", "NSESymbol": "JSWENERGY", "Sector": "Power", "ISIN": "INE121E01018"},
    {"CompanyName": "JSW Holdings Ltd.", "NSESymbol": "JSWHL", "Sector": "Financial Services", "ISIN": "INE824G01012"},
    {"CompanyName": "JSW Infrastructure Ltd.", "NSESymbol": "JSWINFRA", "Sector": "Services", "ISIN": "INE880J01026"},
    {"CompanyName": "JSW Steel Ltd.", "NSESymbol": "JSWSTEEL", "Sector": "Metals & Mining", "ISIN": "INE019A01038"},
    {"CompanyName": "Jaiprakash Power Ventures Ltd.", "NSESymbol": "JPPOWER", "Sector": "Power", "ISIN": "INE351F01018"},
    {"CompanyName": "Jammu & Kashmir Bank Ltd.", "NSESymbol": "J&KBANK", "Sector": "Financial Services", "ISIN": "INE168A01041"},
    {"CompanyName": "Jindal Saw Ltd.", "NSESymbol": "JINDALSAW", "Sector": "Capital Goods", "ISIN": "INE324A01032"},
    {"CompanyName": "Jindal Stainless Ltd.", "NSESymbol": "JSL", "Sector": "Metals & Mining", "ISIN": "INE220G01021"},
    {"CompanyName": "Jindal Steel & Power Ltd.", "NSESymbol": "JINDALSTEL", "Sector": "Metals & Mining", "ISIN": "INE749A01030"},
    {"CompanyName": "Jio Financial Services Ltd.", "NSESymbol": "JIOFIN", "Sector": "Financial Services", "ISIN": "INE758E01017"},
    {"CompanyName": "Jubilant Foodworks Ltd.", "NSESymbol": "JUBLFOOD", "Sector": "Consumer Services", "ISIN": "INE797F01020"},
    {"CompanyName": "Jubilant Ingrevia Ltd.", "NSESymbol": "JUBLINGREA", "Sector": "Chemicals", "ISIN": "INE0BY001018"},
    {"CompanyName": "Jubilant Pharmova Ltd.", "NSESymbol": "JUBLPHARMA", "Sector": "Healthcare", "ISIN": "INE700A01033"},
    {"CompanyName": "Jupiter Wagons Ltd.", "NSESymbol": "JWL", "Sector": "Capital Goods", "ISIN": "INE209L01016"},
    {"CompanyName": "Justdial Ltd.", "NSESymbol": "JUSTDIAL", "Sector": "Consumer Services", "ISIN": "INE599M01018"},
    {"CompanyName": "Jyothy Labs Ltd.", "NSESymbol": "JYOTHYLAB", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE668F01031"},
    {"CompanyName": "Jyoti CNC Automation Ltd.", "NSESymbol": "JYOTICNC", "Sector": "Capital Goods", "ISIN": "INE980O01024"},
    {"CompanyName": "K.P.R. Mill Ltd.", "NSESymbol": "KPRMILL", "Sector": "Textiles", "ISIN": "INE930H01031"},
    {"CompanyName": "KEI Industries Ltd.", "NSESymbol": "KEI", "Sector": "Capital Goods", "ISIN": "INE878B01027"},
    {"CompanyName": "KNR Constructions Ltd.", "NSESymbol": "KNRCON", "Sector": "Construction", "ISIN": "INE634I01029"},
    {"CompanyName": "KPIT Technologies Ltd.", "NSESymbol": "KPITTECH", "Sector": "Information Technology", "ISIN": "INE04I401011"},
    {"CompanyName": "Kajaria Ceramics Ltd.", "NSESymbol": "KAJARIACER", "Sector": "Consumer Durables", "ISIN": "INE217B01036"},
    {"CompanyName": "Kalpataru Projects International Ltd.", "NSESymbol": "KPIL", "Sector": "Construction", "ISIN": "INE220B01022"},
    {"CompanyName": "Kalyan Jewellers India Ltd.", "NSESymbol": "KALYANKJIL", "Sector": "Consumer Durables", "ISIN": "INE303R01014"},
    {"CompanyName": "Kansai Nerolac Paints Ltd.", "NSESymbol": "KANSAINER", "Sector": "Consumer Durables", "ISIN": "INE531A01024"},
    {"CompanyName": "Karur Vysya Bank Ltd.", "NSESymbol": "KARURVYSYA", "Sector": "Financial Services", "ISIN": "INE036D01028"},
    {"CompanyName": "Kaynes Technology India Ltd.", "NSESymbol": "KAYNES", "Sector": "Capital Goods", "ISIN": "INE918Z01012"},
    {"CompanyName": "Kec International Ltd.", "NSESymbol": "KEC", "Sector": "Construction", "ISIN": "INE389H01022"},
    {"CompanyName": "Kfin Technologies Ltd.", "NSESymbol": "KFINTECH", "Sector": "Financial Services", "ISIN": "INE138Y01010"},
    {"CompanyName": "Kirloskar Brothers Ltd.", "NSESymbol": "KIRLOSBROS", "Sector": "Capital Goods", "ISIN": "INE732A01036"},
    {"CompanyName": "Kirloskar Oil Eng Ltd.", "NSESymbol": "KIRLOSENG", "Sector": "Capital Goods", "ISIN": "INE146L01010"},
    {"CompanyName": "Kotak Mahindra Bank Ltd.", "NSESymbol": "KOTAKBANK", "Sector": "Financial Services", "ISIN": "INE237A01028"},
    {"CompanyName": "Krishna Institute of Medical Sciences Ltd.", "NSESymbol": "KIMS", "Sector": "Healthcare", "ISIN": "INE967H01025"},
    {"CompanyName": "L&T Finance Ltd.", "NSESymbol": "LTF", "Sector": "Financial Services", "ISIN": "INE498L01015"},
    {"CompanyName": "L&T Technology Services Ltd.", "NSESymbol": "LTTS", "Sector": "Information Technology", "ISIN": "INE010V01017"},
    {"CompanyName": "LIC Housing Finance Ltd.", "NSESymbol": "LICHSGFIN", "Sector": "Financial Services", "ISIN": "INE115A01026"},
    {"CompanyName": "LT Foods Ltd.", "NSESymbol": "LTFOODS", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE818H01020"},
    {"CompanyName": "LTIMindtree Ltd.", "NSESymbol": "LTIM", "Sector": "Information Technology", "ISIN": "INE214T01019"},
    {"CompanyName": "Larsen & Toubro Ltd.", "NSESymbol": "LT", "Sector": "Construction", "ISIN": "INE018A01030"},
    {"CompanyName": "Latent View Analytics Ltd.", "NSESymbol": "LATENTVIEW", "Sector": "Information Technology", "ISIN": "INE0I7C01011"},
    {"CompanyName": "Laurus Labs Ltd.", "NSESymbol": "LAURUSLABS", "Sector": "Healthcare", "ISIN": "INE947Q01028"},
    {"CompanyName": "Lemon Tree Hotels Ltd.", "NSESymbol": "LEMONTREE", "Sector": "Consumer Services", "ISIN": "INE970X01018"},
    {"CompanyName": "Life Insurance Corporation of India", "NSESymbol": "LICI", "Sector": "Financial Services", "ISIN": "INE0J1Y01017"},
    {"CompanyName": "Linde India Ltd.", "NSESymbol": "LINDEINDIA", "Sector": "Chemicals", "ISIN": "INE473A01011"},
    {"CompanyName": "Lloyds Metals And Energy Ltd.", "NSESymbol": "LLOYDSME", "Sector": "Metals & Mining", "ISIN": "INE281B01032"},
    {"CompanyName": "Lupin Ltd.", "NSESymbol": "LUPIN", "Sector": "Healthcare", "ISIN": "INE326A01037"},
    {"CompanyName": "MMTC Ltd.", "NSESymbol": "MMTC", "Sector": "Services", "ISIN": "INE123F01029"},
    {"CompanyName": "MRF Ltd.", "NSESymbol": "MRF", "Sector": "Automobile and Auto Components", "ISIN": "INE883A01011"},
    {"CompanyName": "Macrotech Developers Ltd.", "NSESymbol": "LODHA", "Sector": "Realty", "ISIN": "INE670K01029"},
    {"CompanyName": "Mahanagar Gas Ltd.", "NSESymbol": "MGL", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE002S01010"},
    {"CompanyName": "Maharashtra Seamless Ltd.", "NSESymbol": "MAHSEAMLES", "Sector": "Capital Goods", "ISIN": "INE271B01025"},
    {"CompanyName": "Mahindra & Mahindra Financial Services Ltd.", "NSESymbol": "M&MFIN", "Sector": "Financial Services", "ISIN": "INE774D01024"},
    {"CompanyName": "Mahindra & Mahindra Ltd.", "NSESymbol": "M&M", "Sector": "Automobile and Auto Components", "ISIN": "INE101A01026"},
    {"CompanyName": "Manappuram Finance Ltd.", "NSESymbol": "MANAPPURAM", "Sector": "Financial Services", "ISIN": "INE522D01027"},
    {"CompanyName": "Mangalore Refinery & Petrochemicals Ltd.", "NSESymbol": "MRPL", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE103A01014"},
    {"CompanyName": "Mankind Pharma Ltd.", "NSESymbol": "MANKIND", "Sector": "Healthcare", "ISIN": "INE634S01028"},
    {"CompanyName": "Marico Ltd.", "NSESymbol": "MARICO", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE196A01026"},
    {"CompanyName": "Maruti Suzuki India Ltd.", "NSESymbol": "MARUTI", "Sector": "Automobile and Auto Components", "ISIN": "INE585B01010"},
    {"CompanyName": "Mastek Ltd.", "NSESymbol": "MASTEK", "Sector": "Information Technology", "ISIN": "INE759A01021"},
    {"CompanyName": "Max Financial Services Ltd.", "NSESymbol": "MFSL", "Sector": "Financial Services", "ISIN": "INE180A01020"},
    {"CompanyName": "Max Healthcare Institute Ltd.", "NSESymbol": "MAXHEALTH", "Sector": "Healthcare", "ISIN": "INE027H01010"},
    {"CompanyName": "Mazagoan Dock Shipbuilders Ltd.", "NSESymbol": "MAZDOCK", "Sector": "Capital Goods", "ISIN": "INE249Z01020"},
    {"CompanyName": "Metropolis Healthcare Ltd.", "NSESymbol": "METROPOLIS", "Sector": "Healthcare", "ISIN": "INE112L01020"},
    {"CompanyName": "Minda Corporation Ltd.", "NSESymbol": "MINDACORP", "Sector": "Automobile and Auto Components", "ISIN": "INE842C01021"},
    {"CompanyName": "Motherson Sumi Wiring India Ltd.", "NSESymbol": "MSUMI", "Sector": "Automobile and Auto Components", "ISIN": "INE0FS801015"},
    {"CompanyName": "Motilal Oswal Financial Services Ltd.", "NSESymbol": "MOTILALOFS", "Sector": "Financial Services", "ISIN": "INE338I01027"},
    {"CompanyName": "MphasiS Ltd.", "NSESymbol": "MPHASIS", "Sector": "Information Technology", "ISIN": "INE356A01018"},
    {"CompanyName": "Multi Commodity Exchange of India Ltd.", "NSESymbol": "MCX", "Sector": "Financial Services", "ISIN": "INE745G01035"},
    {"CompanyName": "Muthoot Finance Ltd.", "NSESymbol": "MUTHOOTFIN", "Sector": "Financial Services", "ISIN": "INE414G01012"},
    {"CompanyName": "NATCO Pharma Ltd.", "NSESymbol": "NATCOPHARM", "Sector": "Healthcare", "ISIN": "INE987B01026"},
    {"CompanyName": "NBCC (India) Ltd.", "NSESymbol": "NBCC", "Sector": "Construction", "ISIN": "INE095N01031"},
    {"CompanyName": "NCC Ltd.", "NSESymbol": "NCC", "Sector": "Construction", "ISIN": "INE868B01028"},
    {"CompanyName": "NHPC Ltd.", "NSESymbol": "NHPC", "Sector": "Power", "ISIN": "INE848E01016"},
    {"CompanyName": "NLC India Ltd.", "NSESymbol": "NLCINDIA", "Sector": "Power", "ISIN": "INE589A01014"},
    {"CompanyName": "NMDC Ltd.", "NSESymbol": "NMDC", "Sector": "Metals & Mining", "ISIN": "INE584A01023"},
    {"CompanyName": "NMDC Steel Ltd.", "NSESymbol": "NSLNISP", "Sector": "Metals & Mining", "ISIN": "INE0NNS01018"},
    {"CompanyName": "NTPC Green Energy Ltd.", "NSESymbol": "NTPCGREEN", "Sector": "Power", "ISIN": "INE0ONG01011"},
    {"CompanyName": "NTPC Ltd.", "NSESymbol": "NTPC", "Sector": "Power", "ISIN": "INE733E01010"},
    {"CompanyName": "Narayana Hrudayalaya Ltd.", "NSESymbol": "NH", "Sector": "Healthcare", "ISIN": "INE410P01011"},
    {"CompanyName": "National Aluminium Co. Ltd.", "NSESymbol": "NATIONALUM", "Sector": "Metals & Mining", "ISIN": "INE139A01034"},
    {"CompanyName": "Nava Ltd.", "NSESymbol": "NAVA", "Sector": "Power", "ISIN": "INE725A01030"},
    {"CompanyName": "Navin Fluorine International Ltd.", "NSESymbol": "NAVINFLUOR", "Sector": "Chemicals", "ISIN": "INE048G01026"},
    {"CompanyName": "Nestle India Ltd.", "NSESymbol": "NESTLEIND", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE239A01024"},
    {"CompanyName": "Netweb Technologies India Ltd.", "NSESymbol": "NETWEB", "Sector": "Information Technology", "ISIN": "INE0NT901020"},
    {"CompanyName": "Network18 Media & Investments Ltd.", "NSESymbol": "NETWORK18", "Sector": "Media Entertainment & Publication", "ISIN": "INE870H01013"},
    {"CompanyName": "Neuland Laboratories Ltd.", "NSESymbol": "NEULANDLAB", "Sector": "Healthcare", "ISIN": "INE794A01010"},
    {"CompanyName": "Newgen Software Technologies Ltd.", "NSESymbol": "NEWGEN", "Sector": "Information Technology", "ISIN": "INE619B01017"},
    {"CompanyName": "Nippon Life India Asset Management Ltd.", "NSESymbol": "NAM-INDIA", "Sector": "Financial Services", "ISIN": "INE298J01013"},
    {"CompanyName": "Niva Bupa Health Insurance Company Ltd.", "NSESymbol": "NIVABUPA", "Sector": "Financial Services", "ISIN": "INE995S01015"},
    {"CompanyName": "Nuvama Wealth Management Ltd.", "NSESymbol": "NUVAMA", "Sector": "Financial Services", "ISIN": "INE531F01015"},
    {"CompanyName": "Oberoi Realty Ltd.", "NSESymbol": "OBEROIRLTY", "Sector": "Realty", "ISIN": "INE093I01010"},
    {"CompanyName": "Oil & Natural Gas Corporation Ltd.", "NSESymbol": "ONGC", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE213A01029"},
    {"CompanyName": "Oil India Ltd.", "NSESymbol": "OIL", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE274J01014"},
    {"CompanyName": "Ola Electric Mobility Ltd.", "NSESymbol": "OLAELEC", "Sector": "Automobile and Auto Components", "ISIN": "INE0LXG01040"},
    {"CompanyName": "Olectra Greentech Ltd.", "NSESymbol": "OLECTRA", "Sector": "Automobile and Auto Components", "ISIN": "INE260D01016"},
    {"CompanyName": "One 97 Communications Ltd.", "NSESymbol": "PAYTM", "Sector": "Financial Services", "ISIN": "INE982J01020"},
    {"CompanyName": "Oracle Financial Services Software Ltd.", "NSESymbol": "OFSS", "Sector": "Information Technology", "ISIN": "INE881D01027"},
    {"CompanyName": "PB Fintech Ltd.", "NSESymbol": "POLICYBZR", "Sector": "Financial Services", "ISIN": "INE417T01026"},
    {"CompanyName": "PCBL Chemical Ltd.", "NSESymbol": "PCBL", "Sector": "Chemicals", "ISIN": "INE602A01031"},
    {"CompanyName": "PG Electroplast Ltd.", "NSESymbol": "PGEL", "Sector": "Consumer Durables", "ISIN": "INE457L01029"},
    {"CompanyName": "PI Industries Ltd.", "NSESymbol": "PIIND", "Sector": "Chemicals", "ISIN": "INE603J01030"},
    {"CompanyName": "PNB Housing Finance Ltd.", "NSESymbol": "PNBHOUSING", "Sector": "Financial Services", "ISIN": "INE572E01012"},
    {"CompanyName": "PNC Infratech Ltd.", "NSESymbol": "PNCINFRA", "Sector": "Construction", "ISIN": "INE195J01029"},
    {"CompanyName": "PTC Industries Ltd.", "NSESymbol": "PTCIL", "Sector": "Capital Goods", "ISIN": "INE596F01018"},
    {"CompanyName": "PVR INOX Ltd.", "NSESymbol": "PVRINOX", "Sector": "Media Entertainment & Publication", "ISIN": "INE191H01014"},
    {"CompanyName": "Page Industries Ltd.", "NSESymbol": "PAGEIND", "Sector": "Textiles", "ISIN": "INE761H01022"},
    {"CompanyName": "Patanjali Foods Ltd.", "NSESymbol": "PATANJALI", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE619A01035"},
    {"CompanyName": "Persistent Systems Ltd.", "NSESymbol": "PERSISTENT", "Sector": "Information Technology", "ISIN": "INE262H01021"},
    {"CompanyName": "Petronet LNG Ltd.", "NSESymbol": "PETRONET", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE347G01014"},
    {"CompanyName": "Pfizer Ltd.", "NSESymbol": "PFIZER", "Sector": "Healthcare", "ISIN": "INE182A01018"},
    {"CompanyName": "Phoenix Mills Ltd.", "NSESymbol": "PHOENIXLTD", "Sector": "Realty", "ISIN": "INE211B01039"},
    {"CompanyName": "Pidilite Industries Ltd.", "NSESymbol": "PIDILITIND", "Sector": "Chemicals", "ISIN": "INE318A01026"},
    {"CompanyName": "Piramal Enterprises Ltd.", "NSESymbol": "PEL", "Sector": "Financial Services", "ISIN": "INE140A01024"},
    {"CompanyName": "Piramal Pharma Ltd.", "NSESymbol": "PPLPHARMA", "Sector": "Healthcare", "ISIN": "INE0DK501011"},
    {"CompanyName": "Poly Medicure Ltd.", "NSESymbol": "POLYMED", "Sector": "Healthcare", "ISIN": "INE205C01021"},
    {"CompanyName": "Polycab India Ltd.", "NSESymbol": "POLYCAB", "Sector": "Capital Goods", "ISIN": "INE455K01017"},
    {"CompanyName": "Poonawalla Fincorp Ltd.", "NSESymbol": "POONAWALLA", "Sector": "Financial Services", "ISIN": "INE511C01022"},
    {"CompanyName": "Power Finance Corporation Ltd.", "NSESymbol": "PFC", "Sector": "Financial Services", "ISIN": "INE134E01011"},
    {"CompanyName": "Power Grid Corporation of India Ltd.", "NSESymbol": "POWERGRID", "Sector": "Power", "ISIN": "INE752E01010"},
    {"CompanyName": "Praj Industries Ltd.", "NSESymbol": "PRAJIND", "Sector": "Capital Goods", "ISIN": "INE074A01025"},
    {"CompanyName": "Premier Energies Ltd.", "NSESymbol": "PREMIERENE", "Sector": "Capital Goods", "ISIN": "INE0BS701011"},
    {"CompanyName": "Prestige Estates Projects Ltd.", "NSESymbol": "PRESTIGE", "Sector": "Realty", "ISIN": "INE811K01011"},
    {"CompanyName": "Punjab National Bank", "NSESymbol": "PNB", "Sector": "Financial Services", "ISIN": "INE160A01022"},
    {"CompanyName": "R R Kabel Ltd.", "NSESymbol": "RRKABEL", "Sector": "Capital Goods", "ISIN": "INE777K01022"},
    {"CompanyName": "RBL Bank Ltd.", "NSESymbol": "RBLBANK", "Sector": "Financial Services", "ISIN": "INE976G01028"},
    {"CompanyName": "REC Ltd.", "NSESymbol": "RECLTD", "Sector": "Financial Services", "ISIN": "INE020B01018"},
    {"CompanyName": "RHI MAGNESITA INDIA LTD.", "NSESymbol": "RHIM", "Sector": "Capital Goods", "ISIN": "INE743M01012"},
    {"CompanyName": "RITES Ltd.", "NSESymbol": "RITES", "Sector": "Construction", "ISIN": "INE320J01015"},
    {"CompanyName": "Radico Khaitan Ltd", "NSESymbol": "RADICO", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE944F01028"},
    {"CompanyName": "Rail Vikas Nigam Ltd.", "NSESymbol": "RVNL", "Sector": "Construction", "ISIN": "INE415G01027"},
    {"CompanyName": "Railtel Corporation Of India Ltd.", "NSESymbol": "RAILTEL", "Sector": "Telecommunication", "ISIN": "INE0DD101019"},
    {"CompanyName": "Rainbow Childrens Medicare Ltd.", "NSESymbol": "RAINBOW", "Sector": "Healthcare", "ISIN": "INE961O01016"},
    {"CompanyName": "Ramkrishna Forgings Ltd.", "NSESymbol": "RKFORGE", "Sector": "Automobile and Auto Components", "ISIN": "INE399G01023"},
    {"CompanyName": "Rashtriya Chemicals & Fertilizers Ltd.", "NSESymbol": "RCF", "Sector": "Chemicals", "ISIN": "INE027A01015"},
    {"CompanyName": "RattanIndia Enterprises Ltd.", "NSESymbol": "RTNINDIA", "Sector": "Consumer Services", "ISIN": "INE834M01019"},
    {"CompanyName": "Raymond Lifestyle Ltd.", "NSESymbol": "RAYMONDLSL", "Sector": "Textiles", "ISIN": "INE02ID01020"},
    {"CompanyName": "Raymond Ltd.", "NSESymbol": "RAYMOND", "Sector": "Realty", "ISIN": "INE301A01014"},
    {"CompanyName": "Redington Ltd.", "NSESymbol": "REDINGTON", "Sector": "Services", "ISIN": "INE891D01026"},
    {"CompanyName": "Reliance Industries Ltd.", "NSESymbol": "RELIANCE", "Sector": "Oil Gas & Consumable Fuels", "ISIN": "INE002A01018"},
    {"CompanyName": "Reliance Power Ltd.", "NSESymbol": "RPOWER", "Sector": "Power", "ISIN": "INE614G01033"},
    {"CompanyName": "Route Mobile Ltd.", "NSESymbol": "ROUTE", "Sector": "Telecommunication", "ISIN": "INE450U01017"},
    {"CompanyName": "SBFC Finance Ltd.", "NSESymbol": "SBFC", "Sector": "Financial Services", "ISIN": "INE423Y01016"},
    {"CompanyName": "SBI Cards and Payment Services Ltd.", "NSESymbol": "SBICARD", "Sector": "Financial Services", "ISIN": "INE018E01016"},
    {"CompanyName": "SBI Life Insurance Company Ltd.", "NSESymbol": "SBILIFE", "Sector": "Financial Services", "ISIN": "INE123W01016"},
    {"CompanyName": "SJVN Ltd.", "NSESymbol": "SJVN", "Sector": "Power", "ISIN": "INE002L01015"},
    {"CompanyName": "SKF India Ltd.", "NSESymbol": "SKFINDIA", "Sector": "Capital Goods", "ISIN": "INE640A01023"},
    {"CompanyName": "SRF Ltd.", "NSESymbol": "SRF", "Sector": "Chemicals", "ISIN": "INE647A01010"},
    {"CompanyName": "Sagility India Ltd.", "NSESymbol": "SAGILITY", "Sector": "Information Technology", "ISIN": "INE0W2G01015"},
    {"CompanyName": "Sai Life Sciences Ltd.", "NSESymbol": "SAILIFE", "Sector": "Healthcare", "ISIN": "INE570L01029"},
    {"CompanyName": "Sammaan Capital Ltd.", "NSESymbol": "SAMMAANCAP", "Sector": "Financial Services", "ISIN": "INE148I01020"},
    {"CompanyName": "Samvardhana Motherson International Ltd.", "NSESymbol": "MOTHERSON", "Sector": "Automobile and Auto Components", "ISIN": "INE775A01035"},
    {"CompanyName": "Sapphire Foods India Ltd.", "NSESymbol": "SAPPHIRE", "Sector": "Consumer Services", "ISIN": "INE806T01020"},
    {"CompanyName": "Sarda Energy and Minerals Ltd.", "NSESymbol": "SARDAEN", "Sector": "Metals & Mining", "ISIN": "INE385C01021"},
    {"CompanyName": "Saregama India Ltd", "NSESymbol": "SAREGAMA", "Sector": "Media Entertainment & Publication", "ISIN": "INE979A01025"},
    {"CompanyName": "Schaeffler India Ltd.", "NSESymbol": "SCHAEFFLER", "Sector": "Automobile and Auto Components", "ISIN": "INE513A01022"},
    {"CompanyName": "Schneider Electric Infrastructure Ltd.", "NSESymbol": "SCHNEIDER", "Sector": "Capital Goods", "ISIN": "INE839M01018"},
    {"CompanyName": "Shipping Corporation of India Ltd.", "NSESymbol": "SCI", "Sector": "Services", "ISIN": "INE109A01011"},
    {"CompanyName": "Shree Cement Ltd.", "NSESymbol": "SHREECEM", "Sector": "Construction Materials", "ISIN": "INE070A01015"},
    {"CompanyName": "Shree Renuka Sugars Ltd.", "NSESymbol": "RENUKA", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE087H01022"},
    {"CompanyName": "Shriram Finance Ltd.", "NSESymbol": "SHRIRAMFIN", "Sector": "Financial Services", "ISIN": "INE721A01047"},
    {"CompanyName": "Shyam Metalics and Energy Ltd.", "NSESymbol": "SHYAMMETL", "Sector": "Capital Goods", "ISIN": "INE810G01011"},
    {"CompanyName": "Siemens Ltd.", "NSESymbol": "SIEMENS", "Sector": "Capital Goods", "ISIN": "INE003A01024"},
    {"CompanyName": "Signatureglobal (India) Ltd.", "NSESymbol": "SIGNATURE", "Sector": "Realty", "ISIN": "INE903U01023"},
    {"CompanyName": "Sobha Ltd.", "NSESymbol": "SOBHA", "Sector": "Realty", "ISIN": "INE671H01015"},
    {"CompanyName": "Solar Industries India Ltd.", "NSESymbol": "SOLARINDS", "Sector": "Chemicals", "ISIN": "INE343H01029"},
    {"CompanyName": "Sona BLW Precision Forgings Ltd.", "NSESymbol": "SONACOMS", "Sector": "Automobile and Auto Components", "ISIN": "INE073K01018"},
    {"CompanyName": "Sonata Software Ltd.", "NSESymbol": "SONATSOFTW", "Sector": "Information Technology", "ISIN": "INE269A01021"},
    {"CompanyName": "Star Health and Allied Insurance Company Ltd.", "NSESymbol": "STARHEALTH", "Sector": "Financial Services", "ISIN": "INE575P01011"},
    {"CompanyName": "State Bank of India", "NSESymbol": "SBIN", "Sector": "Financial Services", "ISIN": "INE062A01020"},
    {"CompanyName": "Steel Authority of India Ltd.", "NSESymbol": "SAIL", "Sector": "Metals & Mining", "ISIN": "INE114A01011"},
    {"CompanyName": "Sterling and Wilson Renewable Energy Ltd.", "NSESymbol": "SWSOLAR", "Sector": "Construction", "ISIN": "INE00M201021"},
    {"CompanyName": "Sumitomo Chemical India Ltd.", "NSESymbol": "SUMICHEM", "Sector": "Chemicals", "ISIN": "INE258G01013"},
    {"CompanyName": "Sun Pharmaceutical Industries Ltd.", "NSESymbol": "SUNPHARMA", "Sector": "Healthcare", "ISIN": "INE044A01036"},
    {"CompanyName": "Sun TV Network Ltd.", "NSESymbol": "SUNTV", "Sector": "Media Entertainment & Publication", "ISIN": "INE424H01027"},
    {"CompanyName": "Sundaram Finance Ltd.", "NSESymbol": "SUNDARMFIN", "Sector": "Financial Services", "ISIN": "INE660A01013"},
    {"CompanyName": "Sundram Fasteners Ltd.", "NSESymbol": "SUNDRMFAST", "Sector": "Automobile and Auto Components", "ISIN": "INE387A01021"},
    {"CompanyName": "Supreme Industries Ltd.", "NSESymbol": "SUPREMEIND", "Sector": "Capital Goods", "ISIN": "INE195A01028"},
    {"CompanyName": "Suzlon Energy Ltd.", "NSESymbol": "SUZLON", "Sector": "Capital Goods", "ISIN": "INE040H01021"},
    {"CompanyName": "Swan Energy Ltd.", "NSESymbol": "SWANENERGY", "Sector": "Chemicals", "ISIN": "INE665A01038"},
    {"CompanyName": "Swiggy Ltd.", "NSESymbol": "SWIGGY", "Sector": "Consumer Services", "ISIN": "INE00H001014"},
    {"CompanyName": "Syngene International Ltd.", "NSESymbol": "SYNGENE", "Sector": "Healthcare", "ISIN": "INE398R01022"},
    {"CompanyName": "Syrma SGS Technology Ltd.", "NSESymbol": "SYRMA", "Sector": "Capital Goods", "ISIN": "INE0DYJ01015"},
    {"CompanyName": "TBO Tek Ltd.", "NSESymbol": "TBOTEK", "Sector": "Consumer Services", "ISIN": "INE673O01025"},
    {"CompanyName": "TVS Motor Company Ltd.", "NSESymbol": "TVSMOTOR", "Sector": "Automobile and Auto Components", "ISIN": "INE494B01023"},
    {"CompanyName": "Tanla Platforms Ltd.", "NSESymbol": "TANLA", "Sector": "Information Technology", "ISIN": "INE483C01032"},
    {"CompanyName": "Tata Chemicals Ltd.", "NSESymbol": "TATACHEM", "Sector": "Chemicals", "ISIN": "INE092A01019"},
    {"CompanyName": "Tata Communications Ltd.", "NSESymbol": "TATACOMM", "Sector": "Telecommunication", "ISIN": "INE151A01013"},
    {"CompanyName": "Tata Consultancy Services Ltd.", "NSESymbol": "TCS", "Sector": "Information Technology", "ISIN": "INE467B01029"},
    {"CompanyName": "Tata Consumer Products Ltd.", "NSESymbol": "TATACONSUM", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE192A01025"},
    {"CompanyName": "Tata Elxsi Ltd.", "NSESymbol": "TATAELXSI", "Sector": "Information Technology", "ISIN": "INE670A01012"},
    {"CompanyName": "Tata Investment Corporation Ltd.", "NSESymbol": "TATAINVEST", "Sector": "Financial Services", "ISIN": "INE672A01018"},
    {"CompanyName": "Tata Motors Ltd.", "NSESymbol": "TATAMOTORS", "Sector": "Automobile and Auto Components", "ISIN": "INE155A01022"},
    {"CompanyName": "Tata Power Co. Ltd.", "NSESymbol": "TATAPOWER", "Sector": "Power", "ISIN": "INE245A01021"},
    {"CompanyName": "Tata Steel Ltd.", "NSESymbol": "TATASTEEL", "Sector": "Metals & Mining", "ISIN": "INE081A01020"},
    {"CompanyName": "Tata Technologies Ltd.", "NSESymbol": "TATATECH", "Sector": "Information Technology", "ISIN": "INE142M01025"},
    {"CompanyName": "Tata Teleservices (Maharashtra) Ltd.", "NSESymbol": "TTML", "Sector": "Telecommunication", "ISIN": "INE517B01013"},
    {"CompanyName": "Tech Mahindra Ltd.", "NSESymbol": "TECHM", "Sector": "Information Technology", "ISIN": "INE669C01036"},
    {"CompanyName": "Techno Electric & Engineering Company Ltd.", "NSESymbol": "TECHNOE", "Sector": "Construction", "ISIN": "INE285K01026"},
    {"CompanyName": "Tejas Networks Ltd.", "NSESymbol": "TEJASNET", "Sector": "Telecommunication", "ISIN": "INE010J01012"},
    {"CompanyName": "The New India Assurance Company Ltd.", "NSESymbol": "NIACL", "Sector": "Financial Services", "ISIN": "INE470Y01017"},
    {"CompanyName": "The Ramco Cements Ltd.", "NSESymbol": "RAMCOCEM", "Sector": "Construction Materials", "ISIN": "INE331A01037"},
    {"CompanyName": "Thermax Ltd.", "NSESymbol": "THERMAX", "Sector": "Capital Goods", "ISIN": "INE152A01029"},
    {"CompanyName": "Timken India Ltd.", "NSESymbol": "TIMKEN", "Sector": "Capital Goods", "ISIN": "INE325A01013"},
    {"CompanyName": "Titagarh Rail Systems Ltd.", "NSESymbol": "TITAGARH", "Sector": "Capital Goods", "ISIN": "INE615H01020"},
    {"CompanyName": "Titan Company Ltd.", "NSESymbol": "TITAN", "Sector": "Consumer Durables", "ISIN": "INE280A01028"},
    {"CompanyName": "Torrent Pharmaceuticals Ltd.", "NSESymbol": "TORNTPHARM", "Sector": "Healthcare", "ISIN": "INE685A01028"},
    {"CompanyName": "Torrent Power Ltd.", "NSESymbol": "TORNTPOWER", "Sector": "Power", "ISIN": "INE813H01021"},
    {"CompanyName": "Transformers And Rectifiers (India) Ltd.", "NSESymbol": "TARIL", "Sector": "Capital Goods", "ISIN": "INE763I01026"},
    {"CompanyName": "Trent Ltd.", "NSESymbol": "TRENT", "Sector": "Consumer Services", "ISIN": "INE849A01020"},
    {"CompanyName": "Trident Ltd.", "NSESymbol": "TRIDENT", "Sector": "Textiles", "ISIN": "INE064C01022"},
    {"CompanyName": "Triveni Engineering & Industries Ltd.", "NSESymbol": "TRIVENI", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE256C01024"},
    {"CompanyName": "Triveni Turbine Ltd.", "NSESymbol": "TRITURBINE", "Sector": "Capital Goods", "ISIN": "INE152M01016"},
    {"CompanyName": "Tube Investments of India Ltd.", "NSESymbol": "TIINDIA", "Sector": "Automobile and Auto Components", "ISIN": "INE974X01010"},
    {"CompanyName": "UCO Bank", "NSESymbol": "UCOBANK", "Sector": "Financial Services", "ISIN": "INE691A01018"},
    {"CompanyName": "UNO Minda Ltd.", "NSESymbol": "UNOMINDA", "Sector": "Automobile and Auto Components", "ISIN": "INE405E01023"},
    {"CompanyName": "UPL Ltd.", "NSESymbol": "UPL", "Sector": "Chemicals", "ISIN": "INE628A01036"},
    {"CompanyName": "UTI Asset Management Company Ltd.", "NSESymbol": "UTIAMC", "Sector": "Financial Services", "ISIN": "INE094J01016"},
    {"CompanyName": "UltraTech Cement Ltd.", "NSESymbol": "ULTRACEMCO", "Sector": "Construction Materials", "ISIN": "INE481G01011"},
    {"CompanyName": "Union Bank of India", "NSESymbol": "UNIONBANK", "Sector": "Financial Services", "ISIN": "INE692A01016"},
    {"CompanyName": "United Breweries Ltd.", "NSESymbol": "UBL", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE686F01025"},
    {"CompanyName": "United Spirits Ltd.", "NSESymbol": "UNITDSPR", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE854D01024"},
    {"CompanyName": "Usha Martin Ltd.", "NSESymbol": "USHAMART", "Sector": "Capital Goods", "ISIN": "INE228A01035"},
    {"CompanyName": "V-Guard Industries Ltd.", "NSESymbol": "VGUARD", "Sector": "Consumer Durables", "ISIN": "INE951I01027"},
    {"CompanyName": "Valor Estate Ltd.", "NSESymbol": "DBREALTY", "Sector": "Consumer Services", "ISIN": "INE879I01012"},
    {"CompanyName": "Vardhman Textiles Ltd.", "NSESymbol": "VTL", "Sector": "Textiles", "ISIN": "INE825A01020"},
    {"CompanyName": "Varun Beverages Ltd.", "NSESymbol": "VBL", "Sector": "Fast Moving Consumer Goods", "ISIN": "INE200M01039"},
    {"CompanyName": "Vedant Fashions Ltd.", "NSESymbol": "MANYAVAR", "Sector": "Consumer Services", "ISIN": "INE825V01034"},
    {"CompanyName": "Vedanta Ltd.", "NSESymbol": "VEDL", "Sector": "Metals & Mining", "ISIN": "INE205A01025"},
    {"CompanyName": "Vijaya Diagnostic Centre Ltd.", "NSESymbol": "VIJAYA", "Sector": "Healthcare", "ISIN": "INE043W01024"},
    {"CompanyName": "Vishal Mega Mart Ltd.", "NSESymbol": "VMM", "Sector": "Consumer Services", "ISIN": "INE01EA01019"},
    {"CompanyName": "Vodafone Idea Ltd.", "NSESymbol": "IDEA", "Sector": "Telecommunication", "ISIN": "INE669E01016"},
    {"CompanyName": "Voltas Ltd.", "NSESymbol": "VOLTAS", "Sector": "Consumer Durables", "ISIN": "INE226A01021"},
    {"CompanyName": "Waaree Energies Ltd.", "NSESymbol": "WAAREEENER", "Sector": "Capital Goods", "ISIN": "INE377N01017"},
    {"CompanyName": "Welspun Corp Ltd.", "NSESymbol": "WELCORP", "Sector": "Capital Goods", "ISIN": "INE191B01025"},
    {"CompanyName": "Welspun Living Ltd.", "NSESymbol": "WELSPUNLIV", "Sector": "Textiles", "ISIN": "INE192B01031"},
    {"CompanyName": "Westlife Foodworld Ltd.", "NSESymbol": "WESTLIFE", "Sector": "Consumer Services", "ISIN": "INE274F01020"},
    {"CompanyName": "Whirlpool of India Ltd.", "NSESymbol": "WHIRLPOOL", "Sector": "Consumer Durables", "ISIN": "INE716A01013"},
    {"CompanyName": "Wipro Ltd.", "NSESymbol": "WIPRO", "Sector": "Information Technology", "ISIN": "INE075A01022"},
    {"CompanyName": "Wockhardt Ltd.", "NSESymbol": "WOCKPHARMA", "Sector": "Healthcare", "ISIN": "INE049B01025"},
    {"CompanyName": "Yes Bank Ltd.", "NSESymbol": "YESBANK", "Sector": "Financial Services", "ISIN": "INE528G01035"},
    {"CompanyName": "ZF Commercial Vehicle Control Systems India Ltd.", "NSESymbol": "ZFCVINDIA", "Sector": "Automobile and Auto Components", "ISIN": "INE342J01019"},
    {"CompanyName": "Zee Entertainment Enterprises Ltd.", "NSESymbol": "ZEEL", "Sector": "Media Entertainment & Publication", "ISIN": "INE256A01028"},
    {"CompanyName": "Zen Technologies Ltd.", "NSESymbol": "ZENTEC", "Sector": "Capital Goods", "ISIN": "INE251B01027"},
    {"CompanyName": "Zensar Technologies Ltd.", "NSESymbol": "ZENSARTECH", "Sector": "Information Technology", "ISIN": "INE520A01027"},
    {"CompanyName": "Zydus Lifesciences Ltd.", "NSESymbol": "ZYDUSLIFE", "Sector": "Healthcare", "ISIN": "INE010B01027"},
    {"CompanyName": "eClerx Services Ltd.", "NSESymbol": "ECLERX", "Sector": "Services", "ISIN": "INE738I01010"}
]

class InstrumentManager:
    """Manages the universe of instruments for trading."""
    def __init__(self):
        self.nifty50_df = pd.DataFrame(NIFTY50_INTERNAL_LIST)
        logger.info(f"InstrumentManager initialized with {len(self.nifty50_df)} internal Nifty 50 records.")

    def get_isin_for_nse_symbol(self, nse_symbol: str):
        """
        Returns the ISIN for a single NSE symbol.
        """
        if self.nifty50_df.empty:
            logger.warning("Cannot get ISIN, Nifty50 DataFrame is empty.")
            return None
        
        match = self.nifty50_df[self.nifty50_df['NSESymbol'] == nse_symbol.upper()]
        if not match.empty:
            return match.iloc[0]['ISIN']
        
        logger.warning(f"ISIN not found for NSE Symbol '{nse_symbol}' in internal list.")
        return None